### ISSUE TITLE
Is the dev_data.sql insert into organizations statement missing values for the org_unique_id column?

### ISSUE THREAD

**Issue by drewverlee** [pyregence/pyregence#887]
As the title suggests, I think the  "INSERT INTO organizations" SQL statement in the /src/sql/dev_data/dev_data.sql, is missing the org_unique_id column values because that column is marked as "NOT NULL" (aka you can't have missing values) in the src/sql/tables/user_tables.sql file. 

As a result, when the dev_data.sql file is executed and tries to insert a row with a null in the org_unique_id column, it violates the not null constraint. 

Why does this matter? 

Well, the dev_data.sql would be executed as part of the PostgreSQL database Setup instructions, specifically the "Clojure -M:build-db build-all --dev-data" command. 

If so, the suggested change is just to add that column. e.g go from `INSERT INTO organizations (organization_uid, org_name ... `to  `INSERT INTO organizations (organization_uid, org_unique_id, org_name ...` and then give the inserted rows org_unique_id values, which naively, based off just the name, just assume can be the same as the organization_uid. 

This, if true, raises the potentially more important question: what is the difference between *organization_uid and org_unique_id*?  My guess is that the org_unique_id is generated and used outside the database. 

Thanks for looking into this,

**Comment by Oliver-BE** [comment]
Good catch! You're right that the `dev_data.sql` file should include the `org_unique_id` column for each organization that's being created. Sometimes when we add database columns we forget to update the underlying dev data file because we're mostly working locally with a copy of the production DB and we use change files to add the columns instead. 


Your proposed change is correct; feel free to open a PR with the change included!

`organization_uid` is a unique serial ID for each organization. `org_unique_id` was added to allow us to more ergonomically specify restrictions as to which organizations have access to which features in Pyrecast. For example, there is a fifth forecast tab that's only visible to those who are a part of specific organizations. It's far easier to specify those organizations via an `org_unique_id` such as `"delete-me-inc"` rather than its `organization_uid` (which in the case of `dev_data.sql` would be 2). 

If you haven't already, I'd recommend taking a look at the [/docs directory](https://github.com/pyregence/pyregence/tree/main/docs) for some more context about Pyrecast's architecture. The documents aren't the most up to date but they have some good information in there.

**Comment by drewverlee** [comment]
@Oliver-BE, I have created PR, which I would appreciate you reviewing.  I'm confident it's a good-enough short-term solution, however what you said here:

> org_unique_Id specify restrictions as to which organizations have access to which features in Pyrecast. For example, there is a fifth forecast tab that's only visible to those who are a part of specific organizations.

Raises several more questions in my mind :). It might not be worth digging into them at this point, though. 

Thanks for your help,
Drew

**Comment by Oliver-BE** [comment]
Thanks, Drew! Your PR looked great; I've merged it into `main`.
